platform :ios, '9.0'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
require_relative './react-native-pods'
inhibit_all_warnings!

target 'igloo' do
  use_react_native!

  target 'iglooTests' do
    inherit! :complete
  end

  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'igloo-tvOS' do
  target 'igloo-tvOSTests' do
    inherit! :search_paths
  end
end
