platform :ios, '9.0'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
require_relative './react-native-pods'
inhibit_all_warnings!

target 'igloo' do
  # Pods for igloo
  use_react_native!

  target 'iglooTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'igloo-tvOS' do
  # Pods for igloo-tvOS

  target 'igloo-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
